# Generated by Django 2.0.7 on 2018-07-13 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일 (ID)')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('phone_number', models.CharField(max_length=16, verbose_name='휴대폰 번호')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('is_agreed_1', models.BooleanField(default=False, verbose_name='이용약관 동의여부')),
                ('is_agreed_2', models.BooleanField(default=False, verbose_name='개인정보 처리방침 동의여부')),
                ('usertype', models.IntegerField(choices=[(1, '일반 회원'), (2, '아티스트 회원')], default=1, verbose_name='유저 타입')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='아티스트명')),
                ('description', models.TextField(verbose_name='아티스트 소개')),
                ('is_verify', models.BooleanField(default=False, verbose_name='아티스트 인증여부')),
                ('social_fb', models.URLField(verbose_name='소셜_페이스북')),
                ('social_insta', models.URLField(verbose_name='소셜_인스타그램')),
                ('social_youtube', models.URLField(verbose_name='소셜_유튜브')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '아티스트',
                'verbose_name_plural': '아티스트',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist', verbose_name='아티스트'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
