# Generated by Django 2.0.7 on 2018-07-13 17:13

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.accounts.models.artist_image_upload_to)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist', verbose_name='아티스트 사진')),
            ],
            options={
                'verbose_name': '아티스트 사진',
                'verbose_name_plural': '아티스트 사진',
            },
        ),
        migrations.CreateModel(
            name='ArtistMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.FileField(upload_to=apps.accounts.models.artist_movie_upload_to)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist', verbose_name='아티스트 사진')),
            ],
            options={
                'verbose_name': '아티스트 동영상',
                'verbose_name_plural': '아티스트 동영상',
            },
        ),
    ]
