# Generated by Django 2.0.7 on 2018-07-14 11:58

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180714_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[apps.accounts.validators.PhoneNumberValidator()], verbose_name='휴대폰 번호'),
        ),
    ]
