# Generated by Django 2.0.7 on 2018-07-17 17:26

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180714_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[apps.common.validators.PhoneNumberValidator()], verbose_name='휴대폰 번호'),
        ),
    ]
