# Generated by Django 2.0.7 on 2018-07-18 19:19

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180719_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.accounts.models.artist_image_upload_to, verbose_name='사진 1')),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_5',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default=1, upload_to=apps.accounts.models.artist_image_upload_to, verbose_name='사진'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='아티스트명'),
        ),
        migrations.AddField(
            model_name='artistimages',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist', verbose_name='아티스트'),
        ),
    ]
