# Generated by Django 2.0.7 on 2018-07-19 08:30

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180719_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistimages',
            options={'verbose_name': '아티스트 사진', 'verbose_name_plural': '아티스트 사진'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='아티스트명'),
        ),
        migrations.AlterField(
            model_name='artistimages',
            name='image',
            field=models.ImageField(upload_to=apps.accounts.models.artist_image_upload_to_2, verbose_name='사진 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='닉네임'),
        ),
    ]
