# Generated by Django 2.0.7 on 2018-07-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180719_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rate_avg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='평점'),
        ),
    ]
