# Generated by Django 2.0.7 on 2018-10-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180811_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistimagestemp',
            options={'verbose_name': '아티스트 사진 임시저장', 'verbose_name_plural': '아티스트 사진 임시저장'},
        ),
    ]
