# Generated by Django 2.0.7 on 2018-11-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertpost',
            name='title',
        ),
    ]
