# Generated by Django 2.0.7 on 2018-07-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_concert', to='concert.Concert', verbose_name='공연'),
        ),
    ]
