# Generated by Django 2.0.7 on 2018-07-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_auto_20180715_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '답변', 'verbose_name_plural': '답변'},
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': '찜', 'verbose_name_plural': '찜'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '후기', 'verbose_name_plural': '후기'},
        ),
    ]
