# Generated by Django 2.0.7 on 2018-07-25 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0006_auto_20180722_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='후원 금액'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='일괄', max_length=50, verbose_name='사용자 이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
