# Generated by Django 2.0.7 on 2018-08-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0007_auto_20180725_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5, verbose_name='별점'),
        ),
    ]
