# Generated by Django 2.0.7 on 2018-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0008_auto_20180801_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='후원 금액'),
        ),
    ]
