# Generated by Django 2.0.7 on 2018-07-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20180714_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='공연 날짜')),
                ('time', models.TimeField(verbose_name='공연 시간')),
                ('location_1', models.CharField(choices=[('신촌', '신촌'), ('홍대', '홍대'), ('강남', '강남'), ('이태원', '이태원'), ('건대', '건대'), ('한강', '한강'), ('그외', '그외')], max_length=50, verbose_name='공연 장소 1')),
                ('location_2', models.CharField(max_length=100, verbose_name='공연 장소 2')),
                ('description', models.TextField(verbose_name='공연 설명')),
                ('probability', models.IntegerField(verbose_name='공영 확률')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Artist', verbose_name='아티스트')),
            ],
            options={
                'verbose_name': '공연 정보',
                'verbose_name_plural': '공연 정보',
            },
        ),
        migrations.CreateModel(
            name='ConcertSongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='곡 제목')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.Concert', verbose_name='공연')),
            ],
        ),
    ]
