# Generated by Django 2.0.7 on 2018-07-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertsonglist',
            options={'verbose_name': '공연 곡', 'verbose_name_plural': '공연 곡'},
        ),
    ]
