# Generated by Django 2.0.7 on 2018-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_auto_20180714_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='probability',
            field=models.IntegerField(verbose_name='공연 확률'),
        ),
    ]
