# Generated by Django 2.0.7 on 2018-07-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20180715_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertsonglist',
            name='info',
            field=models.CharField(max_length=50, verbose_name='곡 정보'),
            preserve_default=False,
        ),
    ]
