# Generated by Django 2.0.7 on 2018-07-23 04:33

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_auto_20180723_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='probability',
            field=models.PositiveIntegerField(validators=[apps.common.validators.ProbabilityValidator()], verbose_name='공연 확률'),
        ),
    ]
