# Generated by Django 2.0.7 on 2018-07-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0006_auto_20180723_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='공연 설명'),
        ),
    ]
