# Generated by Django 2.0.7 on 2018-07-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0007_auto_20180723_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='location_else',
            field=models.CharField(max_length=50, verbose_name='공연장소 그외'),
        ),
    ]
