# Generated by Django 2.0.7 on 2018-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0009_auto_20180723_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='recommend_yn',
            field=models.BooleanField(default=False, verbose_name='추천 여부'),
        ),
    ]
