# Generated by Django 2.0.7 on 2018-07-31 07:34

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0010_concert_recommend_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2018, 7, 31, 7, 34, 20, 325922, tzinfo=utc), verbose_name='공연 종료 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='rain_cancel',
            field=models.BooleanField(default=True, verbose_name='우천시 취소여부'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='site_reserved',
            field=models.BooleanField(default=True, verbose_name='장소 예약여부'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='probability',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='공연 확률'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='time',
            field=models.TimeField(verbose_name='공연 시작 시간'),
        ),
    ]
