# Generated by Django 2.0.7 on 2018-07-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0011_auto_20180731_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='time',
            new_name='start_time',
        ),
    ]
