# Generated by Django 2.0.7 on 2018-08-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0013_auto_20180731_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='location_else',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='공연장소 그외'),
        ),
    ]
