# Generated by Django 2.0.7 on 2018-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180722_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='csservice',
            name='name',
            field=models.CharField(default='default', max_length=50, verbose_name='문의자 이름'),
            preserve_default=False,
        ),
    ]
