# Generated by Django 2.0.7 on 2018-07-24 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.PositiveIntegerField(choices=[(1000, '1,000 원'), (3000, '3,000 원'), (5000, '5,000 원'), (10000, '10,000 원')], verbose_name='결제 금액'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='후원자'),
        ),
    ]
