# Generated by Django 2.0.7 on 2018-07-24 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180724_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': '후원', 'verbose_name_plural': '후원'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=100, verbose_name='아임포트 거래 ID'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='merchant_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='거래 ID'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패')], db_index=True, default='ready', max_length=9, verbose_name='결제 상태'),
        ),
    ]
