# Generated by Django 2.0.7 on 2018-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20180725_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='message',
            field=models.TextField(default='d', verbose_name='함께 전할 메세지'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='user_name',
            field=models.CharField(default='gkdl', max_length=50, verbose_name='후원자 이름'),
            preserve_default=False,
        ),
    ]
