# Generated by Django 2.0.7 on 2018-07-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20180725_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='merchant_uid',
            field=models.UUIDField(verbose_name='거래 ID'),
        ),
    ]
