# Generated by Django 2.0.7 on 2018-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20180725_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='pay_type',
            field=models.CharField(choices=[('html5_inicis', '카드결제'), ('kakaopay', '카카오페이')], default='html5_inicis', max_length=20, verbose_name='결제수단'),
        ),
    ]
