# Generated by Django 2.0.7 on 2018-07-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20180725_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='rate',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0, verbose_name='별점'),
        ),
    ]
