# Generated by Django 2.0.7 on 2018-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_sponsor_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='rate',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5, verbose_name='별점'),
        ),
    ]
